name: Trigger auto deployment for talent-front

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ development ]
    paths:
    - '**'
    - '.github/workflows/talent-front-AutoDeployTrigger-ea7a4718-75b6-4e56-8c9a-572c52f81020.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TALENTFRONT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TALENTFRONT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TALENTFRONT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: talentmatch.azurecr.io
          registryUsername: ${{ secrets.TALENTFRONT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TALENTFRONT_REGISTRY_PASSWORD }}
          containerAppName: talent-front
          resourceGroup: NetworkWatcherRG
          imageToBuild: talentmatch.azurecr.io/talent-front:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


